apiVersion: v1
kind: Pod
metadata:
  name: webapp
  labels:
    app: webapp
    release: "0"
spec:
  containers:
  - name: webapp
    image: richardchesterwood/k8s-fleetman-webapp-angular:release0
    resources:
      limits:
        memory: "128Mi"
        cpu: "500m"    


---

apiVersion: v1
kind: Pod
metadata:
  name: webapp-release-0-5
  labels:
    app: webapp
    release: "0-5"
spec:
  containers:
  - name: webapp
    image: richardchesterwood/k8s-fleetman-webapp-angular:release0-5
    resources:
      limits:
        memory: "128Mi"
        cpu: "500m"    

---

apiVersion: v1
kind: Pod
metadata:
  name: queue
  labels:
    app: queue    
spec:
  containers:
  - name: activemq
    image: richardchesterwood/k8s-fleetman-queue:release1   